PUT http://localhost:3000/users/b0465443-1584-4349-8443-d111eeaef691
Content-Type: application/json
Accept: application/json

{
    "name": "João Silva",
    "email": "joaosilva@email.com",
    "password": "abcd1234"
}